### ISSUE TITLE
json vs simplejson

### ISSUE THREAD

**Issue by rufuspollock** [okfn/ofs#4]
[Reported 2011-02-22]

Given that, at least up to Python 2.6.5, simplejson is way faster than the standard library json, maybe the following way of importing should be preferred:

<pre>
try:
    import simplejson as json
except ImportError:
    import json
</pre>

See http://shane.willowrise.com/archives/python-json-performance/ that confirms my own results using a slightly deeper structure than a simple dictionary and with the various type of values I need to serialize:

<pre>
from random import randint
from time import time
from uuid import uuid1

from faker import Faker

f = Faker()

def random_phone():
    return {
        'intl_prefix': uuid1(),
        'phonenumber': f.phonenumber(),
        }

def random_address():
    return {
        'email': f.email(),
        'city': f.city(),
        'full_address': f.full_address(),
        'state': f.state(),
        'street_address': f.street_address(),
        'zip_code': f.zip_code(),
        'phones': [random_phone() 
                   for _ in range(randint(1,5))],
        }

def random_company():
    return {
        'guid': uuid1(),
        'company': f.company(),
        'president': f.name(),
        'addresses': [random_address()
                      for _ in range(randint(1,5))],
        'lorem': f.lorem(),
        }

def random_user():
    return {
        'guid': uuid1(),
        'username': f.username(),
        'first_name': f.first_name(),
        'last_name': f.last_name(),
        'addresses': [random_address() 
                      for _ in range(randint(1,5))],
        'companies': [random_company() 
                      for _ in range(randint(1,5))],
        'lorem': f.lorem(),
        }
</pre>

**Comment by cclauss** [comment]
I believe that this should be closed given that Python 2.6 is EOL
* https://devguide.python.org/#branchstatus

**Comment by rufuspollock** [comment]
INVALID.
